// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {network} from '../models';
import {parser} from '../models';
import {minidump} from '../models';

export function AnalyzeAutoexecCommands(arg1:string):Promise<Array<app.AutoexecCommandMatch>>;

export function ApplyAddonListLoadOrderPolicy(arg1:app.AddonListLoadOrderPolicy):Promise<app.AddonListLoadOrderPreview>;

export function ApplyAddonListMerge(arg1:string,arg2:Array<string>):Promise<void>;

export function ApplyModEnableProfile(arg1:string):Promise<app.ModEnableProfileApplyResult>;

export function ApplyModPriorityLayers():Promise<app.AddonListLoadOrderPreview>;

export function ApplyModStrategyGroup(arg1:string,arg2:app.ModStrategyGroupApplyOptions):Promise<app.ModStrategyGroupApplyResult>;

export function AutoDiscoverAddons():Promise<string>;

export function CancelDownloadTask(arg1:string):Promise<void>;

export function CancelPanelMapUpload(arg1:string):Promise<void>;

export function CaptureModEnableProfile(arg1:string,arg2:string):Promise<app.ModEnableProfile>;

export function CaptureModEnableProfileWithAutomation(arg1:string,arg2:string,arg3:boolean):Promise<app.ModEnableProfile>;

export function CaptureModStrategyGroup(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<app.ModStrategyGroup>;

export function CaptureWorkshopCollection(arg1:string):Promise<app.WorkshopCollectionLink>;

export function ChangePanelDifficulty(arg1:string,arg2:string):Promise<string>;

export function ChangePanelMap(arg1:string,arg2:string):Promise<string>;

export function CheckArchiveMoveConflicts(arg1:Array<string>,arg2:string):Promise<Array<app.FileMoveConflict>>;

export function CheckConflicts():Promise<app.ConflictResult>;

export function CheckConflictsForPaths(arg1:Array<string>):Promise<app.ConflictResult>;

export function CheckConflictsWithOptions(arg1:app.ConflictAnalysisOptions):Promise<app.ConflictResult>;

export function CheckFileMoveConflicts(arg1:Array<string>,arg2:string):Promise<Array<app.FileMoveConflict>>;

export function CheckModUpdates():Promise<app.UpdateCheckResult>;

export function CheckUpdate():Promise<app.UpdateInfo>;

export function CheckWorkshopCollectionUpdates():Promise<Array<app.WorkshopCollectionRefreshResult>>;

export function ClearCompletedPanelMapUploads():Promise<void>;

export function ClearCompletedTasks():Promise<void>;

export function ClearExternalGroupSuggestions():Promise<void>;

export function ClearModPriority(arg1:string):Promise<void>;

export function ClearPanelMaps(arg1:string):Promise<string>;

export function CloseCrashReporter():Promise<void>;

export function ConnectToServer(arg1:string):Promise<void>;

export function CreateAddonListBackup():Promise<app.AddonListBackup>;

export function CreateModStrategyGroupFromKeys(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<app.ModStrategyGroup>;

export function DeleteAddonList():Promise<void>;

export function DeleteAddonListBackup(arg1:string):Promise<void>;

export function DeleteCrashReport(arg1:string):Promise<void>;

export function DeleteModDependencies(arg1:string):Promise<void>;

export function DeleteModEnableProfile(arg1:string):Promise<void>;

export function DeleteModIgnoreFiles(arg1:string):Promise<void>;

export function DeleteModStrategyGroup(arg1:string):Promise<void>;

export function DeletePanelMapFile(arg1:string,arg2:string):Promise<string>;

export function DeleteStockWhitelistBatch(arg1:string):Promise<void>;

export function DeleteVPKFile(arg1:string):Promise<void>;

export function DeleteVPKFiles(arg1:Array<string>):Promise<void>;

export function DeleteWorkshopCollection(arg1:string):Promise<void>;

export function DoUpdate(arg1:string):Promise<string>;

export function DownloadWorkshopCollection(arg1:string):Promise<Array<string>>;

export function EnableAllMissingModDependencies():Promise<app.ModDependencyEnableResult>;

export function EnableModDependencies(arg1:string):Promise<app.ModDependencyEnableResult>;

export function ExportGroupingCatalog(arg1:string):Promise<string>;

export function ExportGroupingCatalogDialog():Promise<string>;

export function ExportModEnableProfile(arg1:string):Promise<string>;

export function ExportModEnableProfileToFile(arg1:string,arg2:string):Promise<void>;

export function ExportServersToFile(arg1:string):Promise<string>;

export function ExportSprayFiles(arg1:app.SprayExportRequest):Promise<app.SprayExportResult>;

export function ExportVPKFilesToZip(arg1:Array<string>,arg2:boolean,arg3:boolean):Promise<string>;

export function ExtractVPKFrom7z(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromArchive(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromRar(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromZip(arg1:string,arg2:string):Promise<void>;

export function FetchPanelMapFiles(arg1:string):Promise<Array<app.PanelMapFile>>;

export function FetchPanelMapHotReloadStatus(arg1:string):Promise<app.PanelMapHotReloadStatus>;

export function FetchPanelMapIssues(arg1:string,arg2:Array<string>):Promise<app.PanelMapIssuesResponse>;

export function FetchPanelMapList(arg1:string):Promise<Array<app.PanelCampaign>>;

export function FetchPanelServerStatus(arg1:string):Promise<app.PanelServerStatus>;

export function FetchPlayerList(arg1:string):Promise<Array<app.PlayerInfo>>;

export function FetchServerInfo(arg1:string):Promise<app.ServerInfo>;

export function FetchWorkshopDetail(arg1:string):Promise<app.WorkshopItemDetail>;

export function FetchWorkshopList(arg1:app.WorkshopQueryOptions):Promise<app.WorkshopListResult>;

export function ForceExit():Promise<void>;

export function GenerateStockWhitelistBatchesFromGame():Promise<app.StockWhitelistStatus>;

export function GetAddonListInfo():Promise<app.AddonListInfo>;

export function GetAddonListLoadOrderEntries():Promise<Array<app.AddonListLoadOrderEntry>>;

export function GetAddonListOrder():Promise<Array<string>>;

export function GetAppConfig():Promise<app.ConfigFile>;

export function GetAppVersion():Promise<string>;

export function GetAutoexecCommandHelp(arg1:string):Promise<Array<app.AutoexecCommandHelp>>;

export function GetAutoexecConfig():Promise<app.AutoexecConfig>;

export function GetConfigMigrationVersion():Promise<number>;

export function GetConflictBadges():Promise<Array<app.ConflictBadge>>;

export function GetConflictFixSuggestions():Promise<Array<app.ConflictFixSuggestion>>;

export function GetConflictRecheckStatus():Promise<app.ConflictRecheckStatus>;

export function GetCrashReportDirectory():Promise<string>;

export function GetCurrentBestIP():Promise<string>;

export function GetCurrentBestIPOption():Promise<network.IPOption>;

export function GetDownloadTasks():Promise<Array<app.DownloadTask>>;

export function GetExternalGroupSuggestions():Promise<Array<app.ModGroupSuggestion>>;

export function GetForkInfo():Promise<app.ForkInfo>;

export function GetGroupSuggestionAgentPrompt():Promise<string>;

export function GetGroupSuggestionInboxPath():Promise<string>;

export function GetMapName(arg1:string):Promise<string>;

export function GetMirrors():Promise<Array<string>>;

export function GetMirrorsInitial():Promise<Array<app.MirrorWithLatency>>;

export function GetMirrorsWithLatency():Promise<Array<app.MirrorWithLatency>>;

export function GetModGroupMembership():Promise<Array<app.ModGroupMembership>>;

export function GetModIgnoreFiles(arg1:string):Promise<Array<string>>;

export function GetModPriorityPlan():Promise<Array<app.ModEffectivePriority>>;

export function GetModRotation():Promise<app.RotationConfig>;

export function GetModStrategyGroupMissingMembers():Promise<Array<app.ModStrategyGroupMissingMembers>>;

export function GetModelStatsScanState():Promise<app.ModelStatsScanState>;

export function GetPanelMapUploadTasks():Promise<Array<app.PanelMapUploadTask>>;

export function GetPrimaryTags():Promise<Array<string>>;

export function GetProblemModScanSession():Promise<app.ProblemModScanSession>;

export function GetRootDirectory():Promise<string>;

export function GetSecondaryTags(arg1:string):Promise<Array<string>>;

export function GetServerStorage():Promise<app.ServerStorage>;

export function GetStockWhitelistStatus():Promise<app.StockWhitelistStatus>;

export function GetVPKCardPreviewImage(arg1:string):Promise<string>;

export function GetVPKFiles():Promise<Array<parser.VPKFile>>;

export function GetVPKLoadOrder(arg1:string):Promise<number>;

export function GetVPKModelMetrics(arg1:Array<string>):Promise<Array<app.VPKModelMetric>>;

export function GetVPKOperationWarning(arg1:string):Promise<app.VPKOperationWarning>;

export function GetVPKPreviewImage(arg1:string):Promise<string>;

export function GetWorkshopAutoRedownload():Promise<boolean>;

export function GetWorkshopBrowserTarget():Promise<string>;

export function GetWorkshopDetails(arg1:string):Promise<Array<app.WorkshopFileDetails>>;

export function GetWorkshopDetailsGrouped(arg1:string):Promise<app.WorkshopDetailsResult>;

export function GetWorkshopFixedIP():Promise<string>;

export function GetWorkshopIPOptions():Promise<Array<network.IPOption>>;

export function GetWorkshopMetaEnabled():Promise<boolean>;

export function GetWorkshopPreferredIP():Promise<boolean>;

export function GetWorkshopTranslateCustomBaseURL():Promise<string>;

export function GetWorkshopTranslateCustomModelId():Promise<string>;

export function GetWorkshopTranslateProvider():Promise<string>;

export function GetWorkshopUpdateCheckEnabled():Promise<boolean>;

export function GetWorkshopWatchLaterStorage():Promise<app.WorkshopWatchLaterStorage>;

export function HandleFileDrop(arg1:Array<string>):Promise<app.DropImportResult>;

export function HandleProtocolURL(arg1:string):Promise<void>;

export function HasActiveDownloads():Promise<boolean>;

export function HasActivePanelUploads():Promise<boolean>;

export function HasWorkshopTranslateCustomAPIKey():Promise<boolean>;

export function HotReloadPanelMaps(arg1:string):Promise<app.PanelMapHotReloadResult>;

export function ImportGroupSuggestionsFromFile(arg1:string):Promise<app.GroupSuggestionImportResult>;

export function ImportGroupSuggestionsOpenDialog():Promise<app.GroupSuggestionImportResult>;

export function ImportModEnableProfile():Promise<app.ModEnableProfile>;

export function ImportModEnableProfileFromFile(arg1:string):Promise<app.ModEnableProfile>;

export function InspectVPKIntegrity(arg1:string):Promise<parser.VPKIntegrityReport>;

export function InspectVPKIntegrityBatch(arg1:Array<string>):Promise<Array<app.VPKIntegrityBatchResult>>;

export function InstallCrashReporter():Promise<void>;

export function InstallSprayVPK(arg1:app.SprayInstallRequest):Promise<app.SprayInstallResult>;

export function InvalidateConflictRecheck(arg1:string):Promise<void>;

export function IsSelectingIP():Promise<boolean>;

export function LaunchL4D2():Promise<void>;

export function LaunchL4D2ForProblemScan():Promise<void>;

export function ListAddonListBackups():Promise<Array<app.AddonListBackup>>;

export function ListCrashReports():Promise<Array<app.CrashReport>>;

export function ListLocalStoreBackups(arg1:string):Promise<Array<string>>;

export function ListModDependencies():Promise<Array<app.ModDependencyRecord>>;

export function ListModEnableProfiles():Promise<Array<app.ModEnableProfile>>;

export function ListModIgnoreRecords():Promise<Array<app.ModIgnoreRecord>>;

export function ListModPriorities():Promise<Array<app.ModPriorityEntry>>;

export function ListModStrategyGroupTree():Promise<Array<app.ModStrategyGroupTreeNode>>;

export function ListModStrategyGroups():Promise<Array<app.ModStrategyGroup>>;

export function ListWorkshopCollections():Promise<Array<app.WorkshopCollectionLink>>;

export function LoadSprayImportFiles(arg1:Array<string>):Promise<Array<app.SprayImportFilePayload>>;

export function LogError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ManualRotateMods(arg1:app.RotationConfig):Promise<void>;

export function MigrateLocalStorageConfig(arg1:app.LocalStorageMigrationPayload):Promise<void>;

export function MoveArchiveFiles(arg1:Array<string>,arg2:string,arg3:string):Promise<app.MoveResult>;

export function MoveModStrategyGroup(arg1:string,arg2:string):Promise<app.ModStrategyGroup>;

export function MoveVpkFiles(arg1:Array<string>,arg2:string):Promise<app.MoveResult>;

export function MoveVpkFilesWithConflictAction(arg1:Array<string>,arg2:string,arg3:string):Promise<app.MoveResult>;

export function MoveWorkshopFilesToAddons(arg1:Array<string>):Promise<app.WorkshopTransferResult>;

export function MoveWorkshopToAddons(arg1:string):Promise<void>;

export function MoveWorkshopToAddonsWithConflictAction(arg1:string,arg2:string):Promise<app.MoveResult>;

export function OpenArchivePackage(arg1:string):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function PackVPKDirectory(arg1:string,arg2:string,arg3:boolean):Promise<app.VPKPackResult>;

export function ParseMDMPFile(arg1:string):Promise<minidump.Report>;

export function ParseWorkshopID(arg1:string):Promise<string>;

export function PrepareGroupingWorkspace():Promise<app.GroupingWorkspace>;

export function PreviewAddonListLoadOrderPolicy(arg1:app.AddonListLoadOrderPolicy):Promise<app.AddonListLoadOrderPreview>;

export function PreviewAddonListMerge(arg1:string):Promise<app.AddonListMergePreview>;

export function ReadCrashReport(arg1:string):Promise<app.CrashReport>;

export function RecheckConflictsNow():Promise<app.ConflictRecheckStatus>;

export function RefreshWorkshopCollection(arg1:string):Promise<app.WorkshopCollectionRefreshResult>;

export function ReloadStockWhitelist():Promise<void>;

export function RemoveDuplicateAddonListEntries():Promise<number>;

export function RemoveMissingFileAddonListEntries():Promise<number>;

export function RenameVPKFile(arg1:string,arg2:string):Promise<string>;

export function RepairVPKIntegrity(arg1:string):Promise<app.VPKRepairResult>;

export function RepairVPKIntegrityBatch(arg1:Array<string>):Promise<Array<app.VPKRepairBatchResult>>;

export function ReportFrontendError(arg1:string,arg2:string):Promise<string>;

export function RestartApplication():Promise<void>;

export function RestartPanelServer(arg1:string):Promise<string>;

export function RestoreAddonListBackup(arg1:string):Promise<app.AddonListInfo>;

export function RestoreProblemModScan():Promise<app.ProblemModScanSession>;

export function RetryDownloadTask(arg1:string):Promise<void>;

export function RetryPanelMapUpload(arg1:string):Promise<void>;

export function RotateMods():Promise<void>;

export function RunModHealthCheck(arg1:app.ModHealthCheckOptions):Promise<app.ModHealthReport>;

export function SaveAddonListManagedSnapshot():Promise<app.AddonListInfo>;

export function SaveAppConfig(arg1:app.ConfigFile):Promise<void>;

export function SaveAutoexecConfig(arg1:string):Promise<void>;

export function SaveGroupSuggestionAgentPromptDialog():Promise<string>;

export function SaveModHealthReport(arg1:string):Promise<string>;

export function SaveServerStorage(arg1:app.ServerStorage):Promise<void>;

export function SaveSprayVMT(arg1:app.SpraySaveVMTRequest):Promise<string>;

export function SaveSprayVTF(arg1:app.SpraySaveVTFRequest):Promise<string>;

export function SaveWorkshopWatchLaterStorage(arg1:app.WorkshopWatchLaterStorage):Promise<void>;

export function ScanArchiveDirectory(arg1:string):Promise<Array<app.ArchivePackageInfo>>;

export function ScanArchiveDirectoryWithPasswords(arg1:string,arg2:Record<string, string>):Promise<Array<app.ArchivePackageInfo>>;

export function ScanArchivePackageWithPassword(arg1:string,arg2:string):Promise<app.ArchivePackageInfo>;

export function ScanVPKFiles():Promise<void>;

export function SearchVPKFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<parser.VPKFile>>;

export function SelectAddonListMergeSource():Promise<string>;

export function SelectArchiveDirectory():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectMDMPFile():Promise<string>;

export function SelectPanelMapUploadFiles():Promise<Array<string>>;

export function SelectVPKFile():Promise<string>;

export function SelectVPKPackSourceDirectory():Promise<string>;

export function SelectVPKUnpackOutputDirectory():Promise<string>;

export function SendPanelRconCommand(arg1:string,arg2:string):Promise<string>;

export function SetAddonListGuardEnabled(arg1:boolean):Promise<app.AddonListInfo>;

export function SetDownloadTaskAutoRedownload(arg1:string,arg2:boolean):Promise<void>;

export function SetModDependencies(arg1:string,arg2:Array<string>):Promise<app.ModDependencyRecord>;

export function SetModIgnoreFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<app.ModIgnoreRecord>;

export function SetModPriority(arg1:string,arg2:string,arg3:number):Promise<app.ModPriorityEntry>;

export function SetModRotation(arg1:app.RotationConfig):Promise<void>;

export function SetModStrategyGroupEnabled(arg1:string,arg2:boolean):Promise<app.ModStrategyGroupApplyResult>;

export function SetModStrategyGroupEnforcement(arg1:string,arg2:boolean):Promise<app.ModStrategyGroup>;

export function SetModStrategyGroupTier(arg1:string,arg2:any):Promise<app.ModStrategyGroup>;

export function SetRootDirectory(arg1:string):Promise<void>;

export function SetVPKGameEnabled(arg1:string,arg2:boolean):Promise<number>;

export function SetVPKLoadOrder(arg1:string,arg2:number):Promise<void>;

export function SetVPKTags(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetWorkshopAutoRedownload(arg1:boolean):Promise<void>;

export function SetWorkshopBrowserTarget(arg1:string):Promise<void>;

export function SetWorkshopFixedIP(arg1:string):Promise<void>;

export function SetWorkshopMetaEnabled(arg1:boolean):Promise<void>;

export function SetWorkshopPreferredIP(arg1:boolean):Promise<void>;

export function SetWorkshopTranslateCustomAPIKey(arg1:string):Promise<void>;

export function SetWorkshopTranslateCustomBaseURL(arg1:string):Promise<void>;

export function SetWorkshopTranslateCustomModelId(arg1:string):Promise<void>;

export function SetWorkshopTranslateProvider(arg1:string):Promise<void>;

export function SetWorkshopUpdateCheckEnabled(arg1:boolean):Promise<void>;

export function ShiftModStrategyGroupPriorities(arg1:string,arg2:number):Promise<app.ModStrategyGroupPriorityShift>;

export function StartDownloadTask(arg1:app.WorkshopFileDetails,arg2:boolean):Promise<string>;

export function StartModelStatsScan():Promise<app.ModelStatsScanState>;

export function StartPanelMapUpload(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function StartProblemModScan():Promise<app.ProblemModScanSession>;

export function SubmitProblemModScanResult(arg1:string):Promise<app.ProblemModScanSession>;

export function SuggestModGroups():Promise<Array<app.ModGroupSuggestion>>;

export function TestMirrorsLatency():Promise<void>;

export function ToggleVPKFile(arg1:string):Promise<void>;

export function ToggleVPKVisibility(arg1:string):Promise<string>;

export function TranslateWorkshopDescription(arg1:string):Promise<app.WorkshopTranslationResult>;

export function UnpackVPKFile(arg1:string,arg2:string):Promise<app.VPKUnpackResult>;

export function ValidateDirectory(arg1:string):Promise<void>;

export function ValidateGroupSuggestionsFile(arg1:string):Promise<app.GroupSuggestionValidation>;
