// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeAutoexecCommands(arg1) {
  return window['go']['app']['App']['AnalyzeAutoexecCommands'](arg1);
}

export function ApplyAddonListLoadOrderPolicy(arg1) {
  return window['go']['app']['App']['ApplyAddonListLoadOrderPolicy'](arg1);
}

export function ApplyAddonListMerge(arg1, arg2) {
  return window['go']['app']['App']['ApplyAddonListMerge'](arg1, arg2);
}

export function AutoDiscoverAddons() {
  return window['go']['app']['App']['AutoDiscoverAddons']();
}

export function CancelDownloadTask(arg1) {
  return window['go']['app']['App']['CancelDownloadTask'](arg1);
}

export function CancelPanelMapUpload(arg1) {
  return window['go']['app']['App']['CancelPanelMapUpload'](arg1);
}

export function ChangePanelDifficulty(arg1, arg2) {
  return window['go']['app']['App']['ChangePanelDifficulty'](arg1, arg2);
}

export function ChangePanelMap(arg1, arg2) {
  return window['go']['app']['App']['ChangePanelMap'](arg1, arg2);
}

export function CheckConflicts() {
  return window['go']['app']['App']['CheckConflicts']();
}

export function CheckConflictsForPaths(arg1) {
  return window['go']['app']['App']['CheckConflictsForPaths'](arg1);
}

export function CheckConflictsWithOptions(arg1) {
  return window['go']['app']['App']['CheckConflictsWithOptions'](arg1);
}

export function CheckFileMoveConflicts(arg1, arg2) {
  return window['go']['app']['App']['CheckFileMoveConflicts'](arg1, arg2);
}

export function CheckModUpdates() {
  return window['go']['app']['App']['CheckModUpdates']();
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function ClearCompletedPanelMapUploads() {
  return window['go']['app']['App']['ClearCompletedPanelMapUploads']();
}

export function ClearCompletedTasks() {
  return window['go']['app']['App']['ClearCompletedTasks']();
}

export function ClearPanelMaps(arg1) {
  return window['go']['app']['App']['ClearPanelMaps'](arg1);
}

export function ConnectToServer(arg1) {
  return window['go']['app']['App']['ConnectToServer'](arg1);
}

export function CreateAddonListBackup() {
  return window['go']['app']['App']['CreateAddonListBackup']();
}

export function DeleteAddonList() {
  return window['go']['app']['App']['DeleteAddonList']();
}

export function DeleteAddonListBackup(arg1) {
  return window['go']['app']['App']['DeleteAddonListBackup'](arg1);
}

export function DeletePanelMapFile(arg1, arg2) {
  return window['go']['app']['App']['DeletePanelMapFile'](arg1, arg2);
}

export function DeleteVPKFile(arg1) {
  return window['go']['app']['App']['DeleteVPKFile'](arg1);
}

export function DeleteVPKFiles(arg1) {
  return window['go']['app']['App']['DeleteVPKFiles'](arg1);
}

export function DoUpdate(arg1) {
  return window['go']['app']['App']['DoUpdate'](arg1);
}

export function ExportServersToFile(arg1) {
  return window['go']['app']['App']['ExportServersToFile'](arg1);
}

export function ExportSprayFiles(arg1) {
  return window['go']['app']['App']['ExportSprayFiles'](arg1);
}

export function ExportVPKFilesToZip(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportVPKFilesToZip'](arg1, arg2, arg3);
}

export function ExtractVPKFrom7z(arg1, arg2) {
  return window['go']['app']['App']['ExtractVPKFrom7z'](arg1, arg2);
}

export function ExtractVPKFromArchive(arg1, arg2) {
  return window['go']['app']['App']['ExtractVPKFromArchive'](arg1, arg2);
}

export function ExtractVPKFromRar(arg1, arg2) {
  return window['go']['app']['App']['ExtractVPKFromRar'](arg1, arg2);
}

export function ExtractVPKFromZip(arg1, arg2) {
  return window['go']['app']['App']['ExtractVPKFromZip'](arg1, arg2);
}

export function FetchPanelMapFiles(arg1) {
  return window['go']['app']['App']['FetchPanelMapFiles'](arg1);
}

export function FetchPanelMapHotReloadStatus(arg1) {
  return window['go']['app']['App']['FetchPanelMapHotReloadStatus'](arg1);
}

export function FetchPanelMapIssues(arg1, arg2) {
  return window['go']['app']['App']['FetchPanelMapIssues'](arg1, arg2);
}

export function FetchPanelMapList(arg1) {
  return window['go']['app']['App']['FetchPanelMapList'](arg1);
}

export function FetchPanelServerStatus(arg1) {
  return window['go']['app']['App']['FetchPanelServerStatus'](arg1);
}

export function FetchPlayerList(arg1) {
  return window['go']['app']['App']['FetchPlayerList'](arg1);
}

export function FetchServerInfo(arg1) {
  return window['go']['app']['App']['FetchServerInfo'](arg1);
}

export function FetchWorkshopDetail(arg1) {
  return window['go']['app']['App']['FetchWorkshopDetail'](arg1);
}

export function FetchWorkshopList(arg1) {
  return window['go']['app']['App']['FetchWorkshopList'](arg1);
}

export function ForceExit() {
  return window['go']['app']['App']['ForceExit']();
}

export function GetAddonListInfo() {
  return window['go']['app']['App']['GetAddonListInfo']();
}

export function GetAddonListLoadOrderEntries() {
  return window['go']['app']['App']['GetAddonListLoadOrderEntries']();
}

export function GetAddonListOrder() {
  return window['go']['app']['App']['GetAddonListOrder']();
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetAutoexecCommandHelp(arg1) {
  return window['go']['app']['App']['GetAutoexecCommandHelp'](arg1);
}

export function GetAutoexecConfig() {
  return window['go']['app']['App']['GetAutoexecConfig']();
}

export function GetConfigMigrationVersion() {
  return window['go']['app']['App']['GetConfigMigrationVersion']();
}

export function GetCurrentBestIP() {
  return window['go']['app']['App']['GetCurrentBestIP']();
}

export function GetCurrentBestIPOption() {
  return window['go']['app']['App']['GetCurrentBestIPOption']();
}

export function GetDownloadTasks() {
  return window['go']['app']['App']['GetDownloadTasks']();
}

export function GetForkInfo() {
  return window['go']['app']['App']['GetForkInfo']();
}

export function GetMapName(arg1) {
  return window['go']['app']['App']['GetMapName'](arg1);
}

export function GetMirrors() {
  return window['go']['app']['App']['GetMirrors']();
}

export function GetMirrorsInitial() {
  return window['go']['app']['App']['GetMirrorsInitial']();
}

export function GetMirrorsWithLatency() {
  return window['go']['app']['App']['GetMirrorsWithLatency']();
}

export function GetModRotation() {
  return window['go']['app']['App']['GetModRotation']();
}

export function GetModelStatsScanState() {
  return window['go']['app']['App']['GetModelStatsScanState']();
}

export function GetPanelMapUploadTasks() {
  return window['go']['app']['App']['GetPanelMapUploadTasks']();
}

export function GetPrimaryTags() {
  return window['go']['app']['App']['GetPrimaryTags']();
}

export function GetProblemModScanSession() {
  return window['go']['app']['App']['GetProblemModScanSession']();
}

export function GetRootDirectory() {
  return window['go']['app']['App']['GetRootDirectory']();
}

export function GetSecondaryTags(arg1) {
  return window['go']['app']['App']['GetSecondaryTags'](arg1);
}

export function GetServerStorage() {
  return window['go']['app']['App']['GetServerStorage']();
}

export function GetVPKFiles() {
  return window['go']['app']['App']['GetVPKFiles']();
}

export function GetVPKLoadOrder(arg1) {
  return window['go']['app']['App']['GetVPKLoadOrder'](arg1);
}

export function GetVPKModelMetrics(arg1) {
  return window['go']['app']['App']['GetVPKModelMetrics'](arg1);
}

export function GetVPKPreviewImage(arg1) {
  return window['go']['app']['App']['GetVPKPreviewImage'](arg1);
}

export function GetWorkshopBrowserTarget() {
  return window['go']['app']['App']['GetWorkshopBrowserTarget']();
}

export function GetWorkshopDetails(arg1) {
  return window['go']['app']['App']['GetWorkshopDetails'](arg1);
}

export function GetWorkshopDetailsGrouped(arg1) {
  return window['go']['app']['App']['GetWorkshopDetailsGrouped'](arg1);
}

export function GetWorkshopFixedIP() {
  return window['go']['app']['App']['GetWorkshopFixedIP']();
}

export function GetWorkshopIPOptions() {
  return window['go']['app']['App']['GetWorkshopIPOptions']();
}

export function GetWorkshopMetaEnabled() {
  return window['go']['app']['App']['GetWorkshopMetaEnabled']();
}

export function GetWorkshopPreferredIP() {
  return window['go']['app']['App']['GetWorkshopPreferredIP']();
}

export function GetWorkshopTranslateCustomBaseURL() {
  return window['go']['app']['App']['GetWorkshopTranslateCustomBaseURL']();
}

export function GetWorkshopTranslateCustomModelId() {
  return window['go']['app']['App']['GetWorkshopTranslateCustomModelId']();
}

export function GetWorkshopTranslateProvider() {
  return window['go']['app']['App']['GetWorkshopTranslateProvider']();
}

export function GetWorkshopUpdateCheckEnabled() {
  return window['go']['app']['App']['GetWorkshopUpdateCheckEnabled']();
}

export function GetWorkshopWatchLaterStorage() {
  return window['go']['app']['App']['GetWorkshopWatchLaterStorage']();
}

export function HandleFileDrop(arg1) {
  return window['go']['app']['App']['HandleFileDrop'](arg1);
}

export function HandleProtocolURL(arg1) {
  return window['go']['app']['App']['HandleProtocolURL'](arg1);
}

export function HasActiveDownloads() {
  return window['go']['app']['App']['HasActiveDownloads']();
}

export function HasActivePanelUploads() {
  return window['go']['app']['App']['HasActivePanelUploads']();
}

export function HasWorkshopTranslateCustomAPIKey() {
  return window['go']['app']['App']['HasWorkshopTranslateCustomAPIKey']();
}

export function HotReloadPanelMaps(arg1) {
  return window['go']['app']['App']['HotReloadPanelMaps'](arg1);
}

export function InspectVPKIntegrity(arg1) {
  return window['go']['app']['App']['InspectVPKIntegrity'](arg1);
}

export function InspectVPKIntegrityBatch(arg1) {
  return window['go']['app']['App']['InspectVPKIntegrityBatch'](arg1);
}

export function InstallSprayVPK(arg1) {
  return window['go']['app']['App']['InstallSprayVPK'](arg1);
}

export function IsSelectingIP() {
  return window['go']['app']['App']['IsSelectingIP']();
}

export function LaunchL4D2() {
  return window['go']['app']['App']['LaunchL4D2']();
}

export function LaunchL4D2ForProblemScan() {
  return window['go']['app']['App']['LaunchL4D2ForProblemScan']();
}

export function ListAddonListBackups() {
  return window['go']['app']['App']['ListAddonListBackups']();
}

export function LoadSprayImportFiles(arg1) {
  return window['go']['app']['App']['LoadSprayImportFiles'](arg1);
}

export function LogError(arg1, arg2, arg3) {
  return window['go']['app']['App']['LogError'](arg1, arg2, arg3);
}

export function ManualRotateMods(arg1) {
  return window['go']['app']['App']['ManualRotateMods'](arg1);
}

export function MigrateLocalStorageConfig(arg1) {
  return window['go']['app']['App']['MigrateLocalStorageConfig'](arg1);
}

export function MoveVpkFiles(arg1, arg2) {
  return window['go']['app']['App']['MoveVpkFiles'](arg1, arg2);
}

export function MoveVpkFilesWithConflictAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['MoveVpkFilesWithConflictAction'](arg1, arg2, arg3);
}

export function MoveWorkshopToAddons(arg1) {
  return window['go']['app']['App']['MoveWorkshopToAddons'](arg1);
}

export function MoveWorkshopToAddonsWithConflictAction(arg1, arg2) {
  return window['go']['app']['App']['MoveWorkshopToAddonsWithConflictAction'](arg1, arg2);
}

export function OpenFileLocation(arg1) {
  return window['go']['app']['App']['OpenFileLocation'](arg1);
}

export function PackVPKDirectory(arg1, arg2, arg3) {
  return window['go']['app']['App']['PackVPKDirectory'](arg1, arg2, arg3);
}

export function ParseMDMPFile(arg1) {
  return window['go']['app']['App']['ParseMDMPFile'](arg1);
}

export function ParseWorkshopID(arg1) {
  return window['go']['app']['App']['ParseWorkshopID'](arg1);
}

export function PreviewAddonListLoadOrderPolicy(arg1) {
  return window['go']['app']['App']['PreviewAddonListLoadOrderPolicy'](arg1);
}

export function PreviewAddonListMerge(arg1) {
  return window['go']['app']['App']['PreviewAddonListMerge'](arg1);
}

export function RenameVPKFile(arg1, arg2) {
  return window['go']['app']['App']['RenameVPKFile'](arg1, arg2);
}

export function RepairVPKIntegrity(arg1) {
  return window['go']['app']['App']['RepairVPKIntegrity'](arg1);
}

export function RepairVPKIntegrityBatch(arg1) {
  return window['go']['app']['App']['RepairVPKIntegrityBatch'](arg1);
}

export function RestartApplication() {
  return window['go']['app']['App']['RestartApplication']();
}

export function RestartPanelServer(arg1) {
  return window['go']['app']['App']['RestartPanelServer'](arg1);
}

export function RestoreAddonListBackup(arg1) {
  return window['go']['app']['App']['RestoreAddonListBackup'](arg1);
}

export function RestoreProblemModScan() {
  return window['go']['app']['App']['RestoreProblemModScan']();
}

export function RetryDownloadTask(arg1) {
  return window['go']['app']['App']['RetryDownloadTask'](arg1);
}

export function RetryPanelMapUpload(arg1) {
  return window['go']['app']['App']['RetryPanelMapUpload'](arg1);
}

export function RotateMods() {
  return window['go']['app']['App']['RotateMods']();
}

export function SaveAddonListManagedSnapshot() {
  return window['go']['app']['App']['SaveAddonListManagedSnapshot']();
}

export function SaveAppConfig(arg1) {
  return window['go']['app']['App']['SaveAppConfig'](arg1);
}

export function SaveAutoexecConfig(arg1) {
  return window['go']['app']['App']['SaveAutoexecConfig'](arg1);
}

export function SaveServerStorage(arg1) {
  return window['go']['app']['App']['SaveServerStorage'](arg1);
}

export function SaveSprayVMT(arg1) {
  return window['go']['app']['App']['SaveSprayVMT'](arg1);
}

export function SaveSprayVTF(arg1) {
  return window['go']['app']['App']['SaveSprayVTF'](arg1);
}

export function SaveWorkshopWatchLaterStorage(arg1) {
  return window['go']['app']['App']['SaveWorkshopWatchLaterStorage'](arg1);
}

export function ScanVPKFiles() {
  return window['go']['app']['App']['ScanVPKFiles']();
}

export function SearchVPKFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchVPKFiles'](arg1, arg2, arg3);
}

export function SelectAddonListMergeSource() {
  return window['go']['app']['App']['SelectAddonListMergeSource']();
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['app']['App']['SelectFiles']();
}

export function SelectMDMPFile() {
  return window['go']['app']['App']['SelectMDMPFile']();
}

export function SelectPanelMapUploadFiles() {
  return window['go']['app']['App']['SelectPanelMapUploadFiles']();
}

export function SelectVPKFile() {
  return window['go']['app']['App']['SelectVPKFile']();
}

export function SelectVPKPackSourceDirectory() {
  return window['go']['app']['App']['SelectVPKPackSourceDirectory']();
}

export function SelectVPKUnpackOutputDirectory() {
  return window['go']['app']['App']['SelectVPKUnpackOutputDirectory']();
}

export function SendPanelRconCommand(arg1, arg2) {
  return window['go']['app']['App']['SendPanelRconCommand'](arg1, arg2);
}

export function SetAddonListGuardEnabled(arg1) {
  return window['go']['app']['App']['SetAddonListGuardEnabled'](arg1);
}

export function SetModRotation(arg1) {
  return window['go']['app']['App']['SetModRotation'](arg1);
}

export function SetRootDirectory(arg1) {
  return window['go']['app']['App']['SetRootDirectory'](arg1);
}

export function SetVPKGameEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetVPKGameEnabled'](arg1, arg2);
}

export function SetVPKLoadOrder(arg1, arg2) {
  return window['go']['app']['App']['SetVPKLoadOrder'](arg1, arg2);
}

export function SetVPKTags(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetVPKTags'](arg1, arg2, arg3);
}

export function SetWorkshopBrowserTarget(arg1) {
  return window['go']['app']['App']['SetWorkshopBrowserTarget'](arg1);
}

export function SetWorkshopFixedIP(arg1) {
  return window['go']['app']['App']['SetWorkshopFixedIP'](arg1);
}

export function SetWorkshopMetaEnabled(arg1) {
  return window['go']['app']['App']['SetWorkshopMetaEnabled'](arg1);
}

export function SetWorkshopPreferredIP(arg1) {
  return window['go']['app']['App']['SetWorkshopPreferredIP'](arg1);
}

export function SetWorkshopTranslateCustomAPIKey(arg1) {
  return window['go']['app']['App']['SetWorkshopTranslateCustomAPIKey'](arg1);
}

export function SetWorkshopTranslateCustomBaseURL(arg1) {
  return window['go']['app']['App']['SetWorkshopTranslateCustomBaseURL'](arg1);
}

export function SetWorkshopTranslateCustomModelId(arg1) {
  return window['go']['app']['App']['SetWorkshopTranslateCustomModelId'](arg1);
}

export function SetWorkshopTranslateProvider(arg1) {
  return window['go']['app']['App']['SetWorkshopTranslateProvider'](arg1);
}

export function SetWorkshopUpdateCheckEnabled(arg1) {
  return window['go']['app']['App']['SetWorkshopUpdateCheckEnabled'](arg1);
}

export function StartDownloadTask(arg1, arg2) {
  return window['go']['app']['App']['StartDownloadTask'](arg1, arg2);
}

export function StartModelStatsScan() {
  return window['go']['app']['App']['StartModelStatsScan']();
}

export function StartPanelMapUpload(arg1, arg2) {
  return window['go']['app']['App']['StartPanelMapUpload'](arg1, arg2);
}

export function StartProblemModScan() {
  return window['go']['app']['App']['StartProblemModScan']();
}

export function SubmitProblemModScanResult(arg1) {
  return window['go']['app']['App']['SubmitProblemModScanResult'](arg1);
}

export function TestMirrorsLatency() {
  return window['go']['app']['App']['TestMirrorsLatency']();
}

export function ToggleVPKFile(arg1) {
  return window['go']['app']['App']['ToggleVPKFile'](arg1);
}

export function ToggleVPKVisibility(arg1) {
  return window['go']['app']['App']['ToggleVPKVisibility'](arg1);
}

export function TranslateWorkshopDescription(arg1) {
  return window['go']['app']['App']['TranslateWorkshopDescription'](arg1);
}

export function UnpackVPKFile(arg1, arg2) {
  return window['go']['app']['App']['UnpackVPKFile'](arg1, arg2);
}

export function ValidateDirectory(arg1) {
  return window['go']['app']['App']['ValidateDirectory'](arg1);
}
