// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {network} from '../models';
import {parser} from '../models';
import {minidump} from '../models';

export function AnalyzeAutoexecCommands(arg1:string):Promise<Array<app.AutoexecCommandMatch>>;

export function ApplyAddonListLoadOrderPolicy(arg1:app.AddonListLoadOrderPolicy):Promise<app.AddonListLoadOrderPreview>;

export function ApplyAddonListMerge(arg1:string,arg2:Array<string>):Promise<void>;

export function AutoDiscoverAddons():Promise<string>;

export function CancelDownloadTask(arg1:string):Promise<void>;

export function CancelPanelMapUpload(arg1:string):Promise<void>;

export function ChangePanelDifficulty(arg1:string,arg2:string):Promise<string>;

export function ChangePanelMap(arg1:string,arg2:string):Promise<string>;

export function CheckConflicts():Promise<app.ConflictResult>;

export function CheckConflictsForPaths(arg1:Array<string>):Promise<app.ConflictResult>;

export function CheckConflictsWithOptions(arg1:app.ConflictAnalysisOptions):Promise<app.ConflictResult>;

export function CheckFileMoveConflicts(arg1:Array<string>,arg2:string):Promise<Array<app.FileMoveConflict>>;

export function CheckModUpdates():Promise<app.UpdateCheckResult>;

export function CheckUpdate():Promise<app.UpdateInfo>;

export function ClearCompletedPanelMapUploads():Promise<void>;

export function ClearCompletedTasks():Promise<void>;

export function ClearPanelMaps(arg1:string):Promise<string>;

export function ConnectToServer(arg1:string):Promise<void>;

export function CreateAddonListBackup():Promise<app.AddonListBackup>;

export function DeleteAddonList():Promise<void>;

export function DeleteAddonListBackup(arg1:string):Promise<void>;

export function DeletePanelMapFile(arg1:string,arg2:string):Promise<string>;

export function DeleteVPKFile(arg1:string):Promise<void>;

export function DeleteVPKFiles(arg1:Array<string>):Promise<void>;

export function DoUpdate(arg1:string):Promise<string>;

export function ExportServersToFile(arg1:string):Promise<string>;

export function ExportSprayFiles(arg1:app.SprayExportRequest):Promise<app.SprayExportResult>;

export function ExportVPKFilesToZip(arg1:Array<string>,arg2:boolean,arg3:boolean):Promise<string>;

export function ExtractVPKFrom7z(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromArchive(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromRar(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromZip(arg1:string,arg2:string):Promise<void>;

export function FetchPanelMapFiles(arg1:string):Promise<Array<app.PanelMapFile>>;

export function FetchPanelMapHotReloadStatus(arg1:string):Promise<app.PanelMapHotReloadStatus>;

export function FetchPanelMapIssues(arg1:string,arg2:Array<string>):Promise<app.PanelMapIssuesResponse>;

export function FetchPanelMapList(arg1:string):Promise<Array<app.PanelCampaign>>;

export function FetchPanelServerStatus(arg1:string):Promise<app.PanelServerStatus>;

export function FetchPlayerList(arg1:string):Promise<Array<app.PlayerInfo>>;

export function FetchServerInfo(arg1:string):Promise<app.ServerInfo>;

export function FetchWorkshopDetail(arg1:string):Promise<app.WorkshopItemDetail>;

export function FetchWorkshopList(arg1:app.WorkshopQueryOptions):Promise<app.WorkshopListResult>;

export function ForceExit():Promise<void>;

export function GetAddonListInfo():Promise<app.AddonListInfo>;

export function GetAddonListLoadOrderEntries():Promise<Array<app.AddonListLoadOrderEntry>>;

export function GetAddonListOrder():Promise<Array<string>>;

export function GetAppConfig():Promise<app.ConfigFile>;

export function GetAppVersion():Promise<string>;

export function GetAutoexecCommandHelp(arg1:string):Promise<Array<app.AutoexecCommandHelp>>;

export function GetAutoexecConfig():Promise<app.AutoexecConfig>;

export function GetConfigMigrationVersion():Promise<number>;

export function GetCurrentBestIP():Promise<string>;

export function GetCurrentBestIPOption():Promise<network.IPOption>;

export function GetDownloadTasks():Promise<Array<app.DownloadTask>>;

export function GetForkInfo():Promise<app.ForkInfo>;

export function GetMapName(arg1:string):Promise<string>;

export function GetMirrors():Promise<Array<string>>;

export function GetMirrorsInitial():Promise<Array<app.MirrorWithLatency>>;

export function GetMirrorsWithLatency():Promise<Array<app.MirrorWithLatency>>;

export function GetModRotation():Promise<app.RotationConfig>;

export function GetModelStatsScanState():Promise<app.ModelStatsScanState>;

export function GetPanelMapUploadTasks():Promise<Array<app.PanelMapUploadTask>>;

export function GetPrimaryTags():Promise<Array<string>>;

export function GetProblemModScanSession():Promise<app.ProblemModScanSession>;

export function GetRootDirectory():Promise<string>;

export function GetSecondaryTags(arg1:string):Promise<Array<string>>;

export function GetServerStorage():Promise<app.ServerStorage>;

export function GetVPKFiles():Promise<Array<parser.VPKFile>>;

export function GetVPKLoadOrder(arg1:string):Promise<number>;

export function GetVPKModelMetrics(arg1:Array<string>):Promise<Array<app.VPKModelMetric>>;

export function GetVPKPreviewImage(arg1:string):Promise<string>;

export function GetWorkshopBrowserTarget():Promise<string>;

export function GetWorkshopDetails(arg1:string):Promise<Array<app.WorkshopFileDetails>>;

export function GetWorkshopDetailsGrouped(arg1:string):Promise<app.WorkshopDetailsResult>;

export function GetWorkshopFixedIP():Promise<string>;

export function GetWorkshopIPOptions():Promise<Array<network.IPOption>>;

export function GetWorkshopMetaEnabled():Promise<boolean>;

export function GetWorkshopPreferredIP():Promise<boolean>;

export function GetWorkshopTranslateCustomBaseURL():Promise<string>;

export function GetWorkshopTranslateCustomModelId():Promise<string>;

export function GetWorkshopTranslateProvider():Promise<string>;

export function GetWorkshopUpdateCheckEnabled():Promise<boolean>;

export function GetWorkshopWatchLaterStorage():Promise<app.WorkshopWatchLaterStorage>;

export function HandleFileDrop(arg1:Array<string>):Promise<app.DropImportResult>;

export function HandleProtocolURL(arg1:string):Promise<void>;

export function HasActiveDownloads():Promise<boolean>;

export function HasActivePanelUploads():Promise<boolean>;

export function HasWorkshopTranslateCustomAPIKey():Promise<boolean>;

export function HotReloadPanelMaps(arg1:string):Promise<app.PanelMapHotReloadResult>;

export function InspectVPKIntegrity(arg1:string):Promise<parser.VPKIntegrityReport>;

export function InspectVPKIntegrityBatch(arg1:Array<string>):Promise<Array<app.VPKIntegrityBatchResult>>;

export function InstallSprayVPK(arg1:app.SprayInstallRequest):Promise<app.SprayInstallResult>;

export function IsSelectingIP():Promise<boolean>;

export function LaunchL4D2():Promise<void>;

export function LaunchL4D2ForProblemScan():Promise<void>;

export function ListAddonListBackups():Promise<Array<app.AddonListBackup>>;

export function LoadSprayImportFiles(arg1:Array<string>):Promise<Array<app.SprayImportFilePayload>>;

export function LogError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ManualRotateMods(arg1:app.RotationConfig):Promise<void>;

export function MigrateLocalStorageConfig(arg1:app.LocalStorageMigrationPayload):Promise<void>;

export function MoveVpkFiles(arg1:Array<string>,arg2:string):Promise<app.MoveResult>;

export function MoveVpkFilesWithConflictAction(arg1:Array<string>,arg2:string,arg3:string):Promise<app.MoveResult>;

export function MoveWorkshopToAddons(arg1:string):Promise<void>;

export function MoveWorkshopToAddonsWithConflictAction(arg1:string,arg2:string):Promise<app.MoveResult>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function PackVPKDirectory(arg1:string,arg2:string,arg3:boolean):Promise<app.VPKPackResult>;

export function ParseMDMPFile(arg1:string):Promise<minidump.Report>;

export function ParseWorkshopID(arg1:string):Promise<string>;

export function PreviewAddonListLoadOrderPolicy(arg1:app.AddonListLoadOrderPolicy):Promise<app.AddonListLoadOrderPreview>;

export function PreviewAddonListMerge(arg1:string):Promise<app.AddonListMergePreview>;

export function RenameVPKFile(arg1:string,arg2:string):Promise<string>;

export function RepairVPKIntegrity(arg1:string):Promise<app.VPKRepairResult>;

export function RepairVPKIntegrityBatch(arg1:Array<string>):Promise<Array<app.VPKRepairBatchResult>>;

export function RestartApplication():Promise<void>;

export function RestartPanelServer(arg1:string):Promise<string>;

export function RestoreAddonListBackup(arg1:string):Promise<app.AddonListInfo>;

export function RestoreProblemModScan():Promise<app.ProblemModScanSession>;

export function RetryDownloadTask(arg1:string):Promise<void>;

export function RetryPanelMapUpload(arg1:string):Promise<void>;

export function RotateMods():Promise<void>;

export function SaveAddonListManagedSnapshot():Promise<app.AddonListInfo>;

export function SaveAppConfig(arg1:app.ConfigFile):Promise<void>;

export function SaveAutoexecConfig(arg1:string):Promise<void>;

export function SaveServerStorage(arg1:app.ServerStorage):Promise<void>;

export function SaveSprayVMT(arg1:app.SpraySaveVMTRequest):Promise<string>;

export function SaveSprayVTF(arg1:app.SpraySaveVTFRequest):Promise<string>;

export function SaveWorkshopWatchLaterStorage(arg1:app.WorkshopWatchLaterStorage):Promise<void>;

export function ScanVPKFiles():Promise<void>;

export function SearchVPKFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<parser.VPKFile>>;

export function SelectAddonListMergeSource():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectMDMPFile():Promise<string>;

export function SelectPanelMapUploadFiles():Promise<Array<string>>;

export function SelectVPKFile():Promise<string>;

export function SelectVPKPackSourceDirectory():Promise<string>;

export function SelectVPKUnpackOutputDirectory():Promise<string>;

export function SendPanelRconCommand(arg1:string,arg2:string):Promise<string>;

export function SetAddonListGuardEnabled(arg1:boolean):Promise<app.AddonListInfo>;

export function SetModRotation(arg1:app.RotationConfig):Promise<void>;

export function SetRootDirectory(arg1:string):Promise<void>;

export function SetVPKGameEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetVPKLoadOrder(arg1:string,arg2:number):Promise<void>;

export function SetVPKTags(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetWorkshopBrowserTarget(arg1:string):Promise<void>;

export function SetWorkshopFixedIP(arg1:string):Promise<void>;

export function SetWorkshopMetaEnabled(arg1:boolean):Promise<void>;

export function SetWorkshopPreferredIP(arg1:boolean):Promise<void>;

export function SetWorkshopTranslateCustomAPIKey(arg1:string):Promise<void>;

export function SetWorkshopTranslateCustomBaseURL(arg1:string):Promise<void>;

export function SetWorkshopTranslateCustomModelId(arg1:string):Promise<void>;

export function SetWorkshopTranslateProvider(arg1:string):Promise<void>;

export function SetWorkshopUpdateCheckEnabled(arg1:boolean):Promise<void>;

export function StartDownloadTask(arg1:app.WorkshopFileDetails,arg2:boolean):Promise<string>;

export function StartModelStatsScan():Promise<app.ModelStatsScanState>;

export function StartPanelMapUpload(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function StartProblemModScan():Promise<app.ProblemModScanSession>;

export function SubmitProblemModScanResult(arg1:string):Promise<app.ProblemModScanSession>;

export function TestMirrorsLatency():Promise<void>;

export function ToggleVPKFile(arg1:string):Promise<void>;

export function ToggleVPKVisibility(arg1:string):Promise<string>;

export function TranslateWorkshopDescription(arg1:string):Promise<app.WorkshopTranslationResult>;

export function UnpackVPKFile(arg1:string,arg2:string):Promise<app.VPKUnpackResult>;

export function ValidateDirectory(arg1:string):Promise<void>;
